[2025-06-10T21:17:05.639+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sentinel_ndvi_processing_pipeline.convert_geotiff_to_cog manual__2025-06-10T21:14:41.936501+00:00 [queued]>
[2025-06-10T21:17:05.644+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sentinel_ndvi_processing_pipeline.convert_geotiff_to_cog manual__2025-06-10T21:14:41.936501+00:00 [queued]>
[2025-06-10T21:17:05.644+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2025-06-10T21:17:05.649+0000] {taskinstance.py:2214} INFO - Executing <Task(BashOperator): convert_geotiff_to_cog> on 2025-06-10 21:14:41.936501+00:00
[2025-06-10T21:17:05.653+0000] {standard_task_runner.py:60} INFO - Started process 120 to run task
[2025-06-10T21:17:05.655+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sentinel_ndvi_processing_pipeline', 'convert_geotiff_to_cog', 'manual__2025-06-10T21:14:41.936501+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/process_sentinel_ndvi_dag.py', '--cfg-path', '/tmp/tmp01awipjq']
[2025-06-10T21:17:05.656+0000] {standard_task_runner.py:88} INFO - Job 50: Subtask convert_geotiff_to_cog
[2025-06-10T21:17:05.681+0000] {task_command.py:423} INFO - Running <TaskInstance: sentinel_ndvi_processing_pipeline.convert_geotiff_to_cog manual__2025-06-10T21:14:41.936501+00:00 [running]> on host 6eee7f84f229
[2025-06-10T21:17:05.731+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sentinel_ndvi_processing_pipeline' AIRFLOW_CTX_TASK_ID='convert_geotiff_to_cog' AIRFLOW_CTX_EXECUTION_DATE='2025-06-10T21:14:41.936501+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-10T21:14:41.936501+00:00'
[2025-06-10T21:17:05.731+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-10T21:17:05.732+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/processing_output && python3 /opt/***/dags/pipeline_tasks/create_cog.py Output file: ndvi_S2A_36SXA_20250610_0_L2A.tif']
[2025-06-10T21:17:05.738+0000] {subprocess.py:86} INFO - Output:
[2025-06-10T21:17:05.955+0000] {subprocess.py:93} INFO - usage: create_cog.py [-h] input_file
[2025-06-10T21:17:05.955+0000] {subprocess.py:93} INFO - create_cog.py: error: unrecognized arguments: file: ndvi_S2A_36SXA_20250610_0_L2A.tif
[2025-06-10T21:17:05.983+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-06-10T21:17:05.989+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-06-10T21:17:05.991+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sentinel_ndvi_processing_pipeline, task_id=convert_geotiff_to_cog, execution_date=20250610T211441, start_date=20250610T211705, end_date=20250610T211705
[2025-06-10T21:17:06.003+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 50 for task convert_geotiff_to_cog (Bash command failed. The command returned a non-zero exit code 2.; 120)
[2025-06-10T21:17:06.028+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-10T21:17:06.037+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
