[2025-06-07T19:13:50.596+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sentinel_ndvi_processing_pipeline.find_latest_sentinel_data manual__2025-06-07T19:13:49.057173+00:00 [queued]>
[2025-06-07T19:13:50.601+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sentinel_ndvi_processing_pipeline.find_latest_sentinel_data manual__2025-06-07T19:13:49.057173+00:00 [queued]>
[2025-06-07T19:13:50.601+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2025-06-07T19:13:50.607+0000] {taskinstance.py:2214} INFO - Executing <Task(BashOperator): find_latest_sentinel_data> on 2025-06-07 19:13:49.057173+00:00
[2025-06-07T19:13:50.610+0000] {standard_task_runner.py:60} INFO - Started process 63 to run task
[2025-06-07T19:13:50.611+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sentinel_ndvi_processing_pipeline', 'find_latest_sentinel_data', 'manual__2025-06-07T19:13:49.057173+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/process_sentinel_ndvi_dag.py', '--cfg-path', '/tmp/tmpslmapb8l']
[2025-06-07T19:13:50.612+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask find_latest_sentinel_data
[2025-06-07T19:13:50.638+0000] {task_command.py:423} INFO - Running <TaskInstance: sentinel_ndvi_processing_pipeline.find_latest_sentinel_data manual__2025-06-07T19:13:49.057173+00:00 [running]> on host 2a7327be99d2
[2025-06-07T19:13:50.677+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sentinel_ndvi_processing_pipeline' AIRFLOW_CTX_TASK_ID='find_latest_sentinel_data' AIRFLOW_CTX_EXECUTION_DATE='2025-06-07T19:13:49.057173+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-07T19:13:49.057173+00:00'
[2025-06-07T19:13:50.678+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-07T19:13:50.678+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/processing_output && python3 /opt/***/scripts/get_latest_sentinel_data.py']
[2025-06-07T19:13:50.686+0000] {subprocess.py:86} INFO - Output:
[2025-06-07T19:13:50.701+0000] {subprocess.py:93} INFO - python3: can't open file '/opt/***/scripts/get_latest_sentinel_data.py': [Errno 2] No such file or directory
[2025-06-07T19:13:50.702+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-06-07T19:13:50.708+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-06-07T19:13:50.709+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sentinel_ndvi_processing_pipeline, task_id=find_latest_sentinel_data, execution_date=20250607T191349, start_date=20250607T191350, end_date=20250607T191350
[2025-06-07T19:13:50.715+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 3 for task find_latest_sentinel_data (Bash command failed. The command returned a non-zero exit code 2.; 63)
[2025-06-07T19:13:50.743+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-07T19:13:50.756+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
