[2025-06-10T20:49:34.267+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sentinel_ndvi_processing_pipeline.find_latest_sentinel_data manual__2025-06-10T20:49:32.413585+00:00 [queued]>
[2025-06-10T20:49:34.274+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sentinel_ndvi_processing_pipeline.find_latest_sentinel_data manual__2025-06-10T20:49:32.413585+00:00 [queued]>
[2025-06-10T20:49:34.274+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2025-06-10T20:49:34.280+0000] {taskinstance.py:2214} INFO - Executing <Task(BashOperator): find_latest_sentinel_data> on 2025-06-10 20:49:32.413585+00:00
[2025-06-10T20:49:34.284+0000] {standard_task_runner.py:60} INFO - Started process 277 to run task
[2025-06-10T20:49:34.286+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sentinel_ndvi_processing_pipeline', 'find_latest_sentinel_data', 'manual__2025-06-10T20:49:32.413585+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/process_sentinel_ndvi_dag.py', '--cfg-path', '/tmp/tmpsaeg03go']
[2025-06-10T20:49:34.286+0000] {standard_task_runner.py:88} INFO - Job 34: Subtask find_latest_sentinel_data
[2025-06-10T20:49:34.310+0000] {task_command.py:423} INFO - Running <TaskInstance: sentinel_ndvi_processing_pipeline.find_latest_sentinel_data manual__2025-06-10T20:49:32.413585+00:00 [running]> on host 66a34d3b63c1
[2025-06-10T20:49:34.350+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sentinel_ndvi_processing_pipeline' AIRFLOW_CTX_TASK_ID='find_latest_sentinel_data' AIRFLOW_CTX_EXECUTION_DATE='2025-06-10T20:49:32.413585+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-10T20:49:32.413585+00:00'
[2025-06-10T20:49:34.351+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-10T20:49:34.351+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/processing_output && python3 /opt/***/dags/pipeline_tasks/get_latest_sentinel_data.py']
[2025-06-10T20:49:34.359+0000] {subprocess.py:86} INFO - Output:
[2025-06-10T20:49:37.123+0000] {subprocess.py:93} INFO - 
[2025-06-10T20:49:37.124+0000] {subprocess.py:93} INFO - ERROR: Failed to save band URLs to JSON file: [Errno 13] Permission denied: 'S2A_36SXA_20250610_0_L2A_bands.json'
[2025-06-10T20:49:37.124+0000] {subprocess.py:93} INFO - Connected to: Earth Search by Element 84
[2025-06-10T20:49:37.124+0000] {subprocess.py:93} INFO - --- Starting data discovery for AOI: Ashdod ---
[2025-06-10T20:49:37.124+0000] {subprocess.py:93} INFO - 
[2025-06-10T20:49:37.124+0000] {subprocess.py:93} INFO - Searching for items in date range: 2025-05-11T20:49:35.285180+00:00/2025-06-10T20:49:35.285180+00:00
[2025-06-10T20:49:37.125+0000] {subprocess.py:93} INFO - Found 8 items in the date range.
[2025-06-10T20:49:37.125+0000] {subprocess.py:93} INFO - 
[2025-06-10T20:49:37.125+0000] {subprocess.py:93} INFO - Processing Item ID: S2A_36SXA_20250610_0_L2A
[2025-06-10T20:49:37.125+0000] {subprocess.py:93} INFO - Acquired on: 2025-06-10 08:31:32.878000+00:00
[2025-06-10T20:49:37.125+0000] {subprocess.py:93} INFO - Found Red band asset URL:
[2025-06-10T20:49:37.125+0000] {subprocess.py:93} INFO - https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/36/S/XA/2025/6/S2A_36SXA_20250610_0_L2A/B04.tif
[2025-06-10T20:49:37.125+0000] {subprocess.py:93} INFO - Found NIR band asset URL:
[2025-06-10T20:49:37.125+0000] {subprocess.py:93} INFO - https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/36/S/XA/2025/6/S2A_36SXA_20250610_0_L2A/B08.tif
[2025-06-10T20:49:37.126+0000] {subprocess.py:93} INFO - Found SCL (cloud mask) asset URL:
[2025-06-10T20:49:37.126+0000] {subprocess.py:93} INFO - https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/36/S/XA/2025/6/S2A_36SXA_20250610_0_L2A/SCL.tif
[2025-06-10T20:49:37.126+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-06-10T20:49:37.126+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/pipeline_tasks/get_latest_sentinel_data.py", line 142, in <module>
[2025-06-10T20:49:37.126+0000] {subprocess.py:93} INFO -     main()
[2025-06-10T20:49:37.126+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/pipeline_tasks/get_latest_sentinel_data.py", line 136, in main
[2025-06-10T20:49:37.126+0000] {subprocess.py:93} INFO -     get_and_save_band_hrefs(latest_item)
[2025-06-10T20:49:37.127+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/pipeline_tasks/get_latest_sentinel_data.py", line 104, in get_and_save_band_hrefs
[2025-06-10T20:49:37.127+0000] {subprocess.py:93} INFO -     with open(output_filename, 'w') as f:
[2025-06-10T20:49:37.127+0000] {subprocess.py:93} INFO - PermissionError: [Errno 13] Permission denied: 'S2A_36SXA_20250610_0_L2A_bands.json'
[2025-06-10T20:49:37.142+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-06-10T20:49:37.148+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-10T20:49:37.149+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=sentinel_ndvi_processing_pipeline, task_id=find_latest_sentinel_data, execution_date=20250610T204932, start_date=20250610T204934, end_date=20250610T204937
[2025-06-10T20:49:37.161+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 34 for task find_latest_sentinel_data (Bash command failed. The command returned a non-zero exit code 1.; 277)
[2025-06-10T20:49:37.183+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-10T20:49:37.195+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
